Exception Student
RoCS2024/student-information-management pull request #11
Opened 2024-03-13 06:00 UTC by katieann7

2024-03-13 08:39 UTC, RoCS2024 commented on student-information-management-application/src/test/java/com/student/information/management/app/facade/student/impl/StudentFacadeImplTest.java
> +        String studentId = "CT21-0073";
What is the purpose of this test method?

2024-03-13 08:40 UTC, RoCS2024 commented on student-information-management-application/src/test/java/com/student/information/management/data/student/dao/impl/StudentDaoImplTest.java
>          Student testStudent = new Student();
why use the actual database? mock it please?

2024-03-13 08:41 UTC, RoCS2024 requested changes
see comments

2024-03-14 10:40 UTC, katieann7 commented
All done po sir.

2024-03-14 11:15 UTC, RoCS2024 commented on student-information-management-application/src/main/java/com/student/information/management/app/model/student/Student.java
> +    private String name;
what is this name field for? you already have last, first and middle name already.

2024-03-14 11:17 UTC, RoCS2024 requested changes
see comments

2024-03-14 23:54 UTC, RoCS2024 approved these changes

2024-03-15 00:01 UTC, RoCS2024 approved these changes

2024-03-15 00:09 UTC, rosellemarithe approved these changes
all goods, please merge it

2024-03-15 00:10 UTC, merged