RCPS-144 Student Information Management: Updating student repeating email address that already exist
RoCS2024/student-information-management pull request #42
Opened 2024-04-16 15:14 UTC by kylmrcdr123

The user can’t use an email address twice or that is already being used inside the system/database.

2024-04-17 16:40 UTC, RoCS2024 commented on src/main/java/com/student/information/management/appl/facade/student/StudentFacade.java
> +    Student findStudentByEmail(String email);
add documentation

2024-04-17 16:41 UTC, RoCS2024 commented on src/main/java/com/student/information/management/data/connection/ConnectionHelper.java
> +    public static final String URL = "jdbc:oracle:thin:@localhost:1521:rogate";
do not change the ssid

2024-04-17 16:41 UTC, RoCS2024 commented on src/main/java/com/student/information/management/data/student/dao/StudentDao.java
> +    Student findStudentByEmail(String email);
add documentation

2024-04-17 16:42 UTC, RoCS2024 requested changes
see comments

2024-04-18 00:06 UTC, kylmrcdr123 commented on src/main/java/com/student/information/management/data/student/dao/StudentDao.java
> +    Student findStudentByEmail(String email);
noted po

2024-04-18 00:42 UTC, RoCS2024 approved these changes
all good

2024-04-18 00:44 UTC, merged